### ISSUE TITLE
Can't deploy built code on EOSIO

### ISSUE THREAD

**Issue by villesundell** [sagan-software/eosio-rust#16]
Thank you, this codebase is very impressive!
But I managed to encounter a problem. When I try to deploy (either by "set code" or "set contract"), I get:

> Reading WASM from /home/ville/eosio-rust/target/wasm32-unknown-unknown/release/hello.wasm...
> Setting Code...
> Error 3070003: Serialization Error Processing WASM
> Error Details:
> Trying to deserialize bytes of size : 84064
> Stack Trace:
> wasm_interface.cpp:46 validate

I have tried to deploy eosio-rust's examples, eosio_token, and my own eosio-rust based test project.

I am able to deploy the official C++ eosio.bios, and my own C++ contracts.
I am also able to deploy my really old rust experiment https://github.com/villesundell/eosio-rust/blob/master/rustcontract.wasm

It seems that something goes wrong while building?

> $ rustc --version
> rustc 1.41.0 (5e1a79984 2020-01-27)

**Comment by kegesch** [comment]
When I ran `wasm-gc` like explained in the book it worked for me.

**Comment by liamcurry** [comment]
Did `wasm-gc` fix the issue @villesundell ?

**Comment by liamcurry** [comment]
@villesundell closing this for now. Please re-open if you're still having trouble deploying the contracts.
